#!/usr/bin/env node
/**
 * generate-wi-tokens.swift.mjs — Emit Swift tokens from shared/warm-instrument/tokens.json
 *
 * Run manually: node ios/scripts/generate-wi-tokens.swift.mjs
 * Wired into Xcode as a pre-build phase on the CoachHQWidgetExtension target
 * (runs before the main app because of the embed dependency).
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../..");
const TOKENS_PATH = path.join(REPO_ROOT, "shared/warm-instrument/tokens.json");
const OUT_PATH = path.join(
  REPO_ROOT,
  "ios/CoachHQ/CoachHQ/Shared/WarmInstrumentTokens.generated.swift",
);

/** tokens.json sport key → WarmSportId Swift case name */
const SPORT_CASE = {
  badminton: "badminton",
  calisthenics: "calisthenics",
  foundation: "foundation",
  cycling: "cycling",
  run: "run",
  strength: "strength",
  weight_training: "weightTraining",
  hike: "hike",
  walk: "walk",
  cricket: "cricket",
  football: "football",
  workout: "workout",
  swim: "swim",
};

function parseRgba(value) {
  const m = value.match(/rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)/);
  if (!m) throw new Error(`unsupported rgba: ${value}`);
  return { r: Number(m[1]), g: Number(m[2]), b: Number(m[3]), a: Number(m[4]) };
}

function parseShadow(value) {
  const m = value.match(/rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)/);
  if (!m) throw new Error(`unsupported shadow: ${value}`);
  return { r: Number(m[1]), g: Number(m[2]), b: Number(m[3]), a: Number(m[4]) };
}

function swiftRgbaColor({ r, g, b, a }) {
  return `Color(red: Double(${r}) / 255, green: Double(${g}) / 255, blue: Double(${b}) / 255).opacity(${a})`;
}

if (!fs.existsSync(TOKENS_PATH)) {
  console.error(`✗ tokens source missing: ${TOKENS_PATH}`);
  process.exit(1);
}

const tokens = JSON.parse(fs.readFileSync(TOKENS_PATH, "utf-8"));

const sportEntries = Object.entries(tokens.sports)
  .map(([id, sport]) => {
    const swiftCase = SPORT_CASE[id];
    if (!swiftCase) return null;
    return `        .${swiftCase}: color(hex: "${sport.hex}"),`;
  })
  .filter(Boolean)
  .join("\n");

const border = parseRgba(tokens.lines.border);
const borderDashed = parseRgba(tokens.lines.borderDashed);
const cardShadow = parseShadow(tokens.shadows.card);
const engineShadow = parseShadow(tokens.shadows.engine);

const swift = `// Generated by ios/scripts/generate-wi-tokens.swift.mjs — do not edit by hand
import SwiftUI
import UIKit

/// Light-mode base values from \`shared/warm-instrument/tokens.json\`.
/// \`Theme\` / \`WarmInstrument\` wrap these in trait-aware \`UIColor\` where dark mode differs.
enum WarmInstrumentTokens {
    static func color(hex: String) -> Color {
        var s = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if s.hasPrefix("#") { s.removeFirst() }
        guard s.count == 6, let v = UInt32(s, radix: 16) else { return Color.primary }
        return Color(
            red: Double((v >> 16) & 0xFF) / 255,
            green: Double((v >> 8) & 0xFF) / 255,
            blue: Double(v & 0xFF) / 255
        )
    }

    static func uiColor(hex: String) -> UIColor {
        var s = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if s.hasPrefix("#") { s.removeFirst() }
        guard s.count == 6, let v = UInt32(s, radix: 16) else { return .label }
        return UIColor(
            red: CGFloat((v >> 16) & 0xFF) / 255,
            green: CGFloat((v >> 8) & 0xFF) / 255,
            blue: CGFloat(v & 0xFF) / 255,
            alpha: 1
        )
    }

    enum Palette {
        static let paper = color(hex: "${tokens.palette.paper}")
        static let desk = color(hex: "${tokens.palette.desk}")
        static let surfaceMuted = color(hex: "${tokens.palette.surfaceMuted}")
        static let ink = color(hex: "${tokens.palette.ink}")
        static let inkMuted = color(hex: "${tokens.palette.inkMuted}")
        static let inkFaint = color(hex: "${tokens.palette.inkFaint}")
        static let accent = color(hex: "${tokens.palette.accent}")
        static let accentDark = color(hex: "${tokens.palette.accentDark}")
        static let alarmBg = color(hex: "${tokens.palette.alarmBg}")
        static let alarmFg = color(hex: "${tokens.palette.alarmFg}")

        enum UI {
            static let paper = uiColor(hex: "${tokens.palette.paper}")
            static let desk = uiColor(hex: "${tokens.palette.desk}")
            static let surfaceMuted = uiColor(hex: "${tokens.palette.surfaceMuted}")
            static let ink = uiColor(hex: "${tokens.palette.ink}")
        }
    }

    enum Lines {
        static func borderUIColor(alpha: CGFloat) -> UIColor {
            UIColor(red: CGFloat(${border.r}) / 255, green: CGFloat(${border.g}) / 255, blue: CGFloat(${border.b}) / 255, alpha: alpha)
        }

        static let border = ${swiftRgbaColor(border)}
        static let borderDashed = ${swiftRgbaColor(borderDashed)}
        static let headerRule = color(hex: "${tokens.lines.headerRule}")
    }

    enum Shadows {
        static let card = ${swiftRgbaColor(cardShadow)}
        static let engine = ${swiftRgbaColor(engineShadow)}
    }

    /// \`radius.cardIosPt\` from tokens.json
    static let cardRadius: CGFloat = ${tokens.radius.cardIosPt}

    /// Static sport palette from \`sports.*.hex\`, keyed by \`WarmSportId\`.
    static let sportColors: [WarmSportId: Color] = [
${sportEntries}
    ]
}
`;

fs.mkdirSync(path.dirname(OUT_PATH), { recursive: true });
fs.writeFileSync(OUT_PATH, swift);
console.log("✓ WarmInstrumentTokens.generated.swift written");
