// Generated by shared/warm-instrument/generate.mjs — do not edit
import SwiftUI

enum WITokens {
    enum Sports {
        static let badminton = Color(red: 0x1A / 255.0, green: 0x47 / 255.0, blue: 0x31 / 255.0)
        static let calisthenics = Color(red: 0x4F / 255.0, green: 0x58 / 255.0, blue: 0x7A / 255.0)
        static let foundation = Color(red: 0x6D / 255.0, green: 0x7D / 255.0, blue: 0x4E / 255.0)
        static let cycling = Color(red: 0xA8 / 255.0, green: 0x70 / 255.0, blue: 0x2C / 255.0)
        static let run = Color(red: 0x37 / 255.0, green: 0x41 / 255.0, blue: 0x51 / 255.0)
        static let strength = Color(red: 0x2D / 255.0, green: 0x3A / 255.0, blue: 0x5A / 255.0)
        static let weightTraining = Color(red: 0x3B / 255.0, green: 0x4A / 255.0, blue: 0x6B / 255.0)
        static let hike = Color(red: 0x7A / 255.0, green: 0x5C / 255.0, blue: 0x3A / 255.0)
        static let walk = Color(red: 0x6B / 255.0, green: 0x72 / 255.0, blue: 0x80 / 255.0)
        static let cricket = Color(red: 0x4A / 255.0, green: 0x67 / 255.0, blue: 0x41 / 255.0)
        static let football = Color(red: 0x16 / 255.0, green: 0x65 / 255.0, blue: 0x34 / 255.0)
        static let workout = Color(red: 0x5B / 255.0, green: 0x64 / 255.0, blue: 0x72 / 255.0)
        static let swim = Color(red: 0x00 / 255.0, green: 0x5F / 255.0, blue: 0x7A / 255.0)
        static let tennis = Color(red: 0xB5 / 255.0, green: 0x53 / 255.0, blue: 0x2A / 255.0)
        static let other = Color(red: 0x8A / 255.0, green: 0x8A / 255.0, blue: 0x8A / 255.0)
    }

    enum Workouts {
        static let foundation = Color(red: 0x4F / 255.0, green: 0x58 / 255.0, blue: 0x7A / 255.0)
        static let calisthenics = Color(red: 0x7F / 255.0, green: 0x37 / 255.0, blue: 0x28 / 255.0)
        static let recovery = Color(red: 0x31 / 255.0, green: 0x5A / 255.0, blue: 0x4A / 255.0)
        static let realign = Color(red: 0xA8 / 255.0, green: 0x70 / 255.0, blue: 0x2C / 255.0)
        static let strength = Color(red: 0x3B / 255.0, green: 0x4A / 255.0, blue: 0x6B / 255.0)
    }

    enum Zones {
        static let ramp: [Color] = [
            Color(red: 0xC3 / 255.0, green: 0xD1 / 255.0, blue: 0xC8 / 255.0),
            Color(red: 0x6F / 255.0, green: 0x90 / 255.0, blue: 0x80 / 255.0),
            Color(red: 0x31 / 255.0, green: 0x5A / 255.0, blue: 0x4A / 255.0),
            Color(red: 0xA8 / 255.0, green: 0x70 / 255.0, blue: 0x2C / 255.0),
            Color(red: 0x7F / 255.0, green: 0x37 / 255.0, blue: 0x28 / 255.0)
        ]
    }
}
