#!/usr/bin/env node
/**
 * build-soul.mjs — bundles platform/SOUL.md into ui/api/_generated/soul.ts so the coach-chat
 * Vercel function can read it as a plain JS import instead of fetching propagated/SOUL.md over
 * the GitHub API from each athlete's own repo every turn. SOUL.md is 100% generic (no per-athlete
 * substitution happens anywhere in the carve process) so it's safe to bundle once, here, and
 * ship it with the function itself - same "generate at build time" pattern build-data.mjs
 * already uses for ui/client/src/data/.
 *
 * Run before dev/build (wired into predev/prebuild in package.json). Fails loudly if
 * platform/SOUL.md is missing rather than silently shipping a stale/empty bundle - but it
 * trusts platform/SOUL.md is *fresh* (i.e. compose-soul.mjs has been re-run after any edit to
 * platform/soul/*.md). It does not itself check that; CI's own drift check
 * (`compose-soul.mjs --check`, see AGENTS.md) is what catches a forgotten recompose - if that
 * check is passing, what this script bundles is guaranteed current.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const SOUL_SRC = path.join(REPO_ROOT, "platform", "SOUL.md");
const OUT_DIR = path.join(__dirname, "..", "api", "_generated");
const OUT_FILE = path.join(OUT_DIR, "soul.ts");

if (!fs.existsSync(SOUL_SRC)) {
  console.error(`build-soul: platform/SOUL.md not found at ${SOUL_SRC} - run compose-soul.mjs first.`);
  process.exit(1);
}

const soul = fs.readFileSync(SOUL_SRC, "utf8");
fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(
  OUT_FILE,
  `// Generated by ui/scripts/build-soul.mjs from platform/SOUL.md - do not edit by hand.\n` +
    `// Regenerate via \`npm run predev\`/\`npm run prebuild\`, or \`node scripts/build-soul.mjs\` directly.\n` +
    `export const SOUL: string = ${JSON.stringify(soul)};\n`,
);

console.log(`build-soul: wrote ${path.relative(REPO_ROOT, OUT_FILE)} (${soul.length} bytes)`);
