#!/usr/bin/env node
/**
 * build-soul.mjs — bundles platform/SOUL.chat.md into ui/api/_generated/soul.ts so the coach-chat
 * Vercel function can read it as a plain JS import instead of fetching a composed SOUL over the
 * GitHub API from each athlete's own repo every turn. The composed SOUL is 100% generic (no
 * per-athlete substitution happens anywhere in the carve process) so it's safe to bundle once,
 * here, and ship it with the function itself - same "generate at build time" pattern
 * build-data.mjs already uses for ui/client/src/data/.
 *
 * Why the `chat` target specifically (ADR 0022): compose-soul.mjs emits two builds from the same
 * platform/soul/*.md layers. `SOUL.claude.md` is the BYO-Claude-Code build - it carries the boot
 * sequence, shell commands, and git ritual, all of which this runtime cannot execute and is
 * explicitly told to ignore. `SOUL.chat.md` is the build addressed to this runtime, so that is
 * the one that ships in the function. Never point this at the other target or at a bare
 * `platform/SOUL.md` - that name is retired precisely so neither runtime silently owns it.
 *
 * Run before dev/build (wired into predev/prebuild in package.json). Fails loudly if
 * platform/SOUL.chat.md is missing rather than silently shipping a stale/empty bundle - but it
 * trusts the file is *fresh* (i.e. compose-soul.mjs has been re-run after any edit to
 * platform/soul/*.md). It does not itself check that; CI's own drift check
 * (`compose-soul.mjs --check`, see AGENTS.md) is what catches a forgotten recompose - if that
 * check is passing, what this script bundles is guaranteed current.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..", "..");
const SOUL_SRC = path.join(REPO_ROOT, "platform", "SOUL.chat.md");
const FIRST_SESSION_SRC = path.join(REPO_ROOT, "platform", "horcruxes", "first-session.md");
const OUT_DIR = path.join(__dirname, "..", "api", "_generated");
const OUT_FILE = path.join(OUT_DIR, "soul.ts");

if (!fs.existsSync(SOUL_SRC)) {
  console.error(`build-soul: platform/SOUL.chat.md not found at ${SOUL_SRC} - run compose-soul.mjs first.`);
  process.exit(1);
}
// Fragments (compose-soul.mjs's HORCRUXES table) are blocks the chat build deliberately does NOT
// carry, injected per-turn instead when the backend's predicate fires - see coachPrompt.ts's
// firstSessionContext(). Missing = the conditional path would silently no-op, so fail here too.
if (!fs.existsSync(FIRST_SESSION_SRC)) {
  console.error(`build-soul: platform/horcruxes/first-session.md not found - run compose-soul.mjs first.`);
  process.exit(1);
}

const soul = fs.readFileSync(SOUL_SRC, "utf8");
const firstSession = fs.readFileSync(FIRST_SESSION_SRC, "utf8");
fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(
  OUT_FILE,
  `// Generated by ui/scripts/build-soul.mjs from platform/SOUL.chat.md - do not edit by hand.\n` +
    `// Regenerate via \`npm run predev\`/\`npm run prebuild\`, or \`node scripts/build-soul.mjs\` directly.\n` +
    `export const SOUL: string = ${JSON.stringify(soul)};\n` +
    `// Conditionally injected - NEVER add to the cached prefix. See coachPrompt.ts.\n` +
    `export const FIRST_SESSION_PROTOCOL: string = ${JSON.stringify(firstSession)};\n`,
);

console.log(
  `build-soul: wrote ${path.relative(REPO_ROOT, OUT_FILE)} (${soul.length} bytes soul, ${firstSession.length} bytes first-session)`,
);
