/**
 * generate-widget-snapshots.ts — Build cross-platform widget snapshot JSON from home models.
 * Invoked by build-data.mjs via tsx.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { generateWidgetSnapshotsFromDashboardSnapshot, type DashboardSnapshotInput } from "../api/auth/_lib/generate-widget-snapshots-from-dashboard-snapshot";
import { repoRoot, widgetSnapshotsPath } from "../../engine/lib/repo-layout.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = repoRoot(path.join(__dirname, ".."));

function readJson<T>(filePath: string, fallback: T): T {
  if (!fs.existsSync(filePath)) return fallback;
  try {
    return JSON.parse(fs.readFileSync(filePath, "utf-8")) as T;
  } catch {
    return fallback;
  }
}

// In local HQ / athlete environments, we read the combined dashboard snapshot output 
// which is already generated by build-data.mjs earlier in the script execution.
const snapshot = readJson<DashboardSnapshotInput | null>(
  path.join(REPO_ROOT, "ui/client/src/data/dashboard_snapshot.json"),
  null,
);

if (!snapshot || !snapshot.ledger) {
  console.warn("⚠ widget_snapshots — no ledger data found in dashboard_snapshot.json, skipping");
  process.exit(0);
}

// The latest coach message is optional.
const latestMessageFile = readJson<unknown>(
  path.join(REPO_ROOT, "ui/client/src/data/latest_message.json"),
  null,
);

const snapshots = generateWidgetSnapshotsFromDashboardSnapshot(snapshot, latestMessageFile);
if (!snapshots) {
  console.warn("⚠ widget_snapshots — failed to generate snapshots from input, skipping");
  process.exit(0);
}

const payload = JSON.stringify(snapshots, null, 2);
const repoOut = widgetSnapshotsPath(REPO_ROOT);
const clientOut = path.join(REPO_ROOT, "ui/client/src/data/widget_snapshots.json");

fs.mkdirSync(path.dirname(repoOut), { recursive: true });
fs.mkdirSync(path.dirname(clientOut), { recursive: true });
fs.writeFileSync(repoOut, payload);
fs.writeFileSync(clientOut, payload);
console.log("✓ widget_snapshots.json written");
