#!/usr/bin/env node
/**
 * generate.mjs — Emit web CSS + iOS Swift colors from tokens.json
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "../..");
const TOKENS_PATH = path.join(__dirname, "tokens.json");
const CSS_OUT = path.join(
  REPO_ROOT,
  "ui/client/src/components/home-warm/wi-tokens.generated.css",
);
const SWIFT_OUT = path.join(
  REPO_ROOT,
  "ios/CoachHQ/CoachHQ/Views/WarmInstrumentTokens.generated.swift",
);

const tokens = JSON.parse(fs.readFileSync(TOKENS_PATH, "utf-8"));

if (!tokens.sports || typeof tokens.sports !== "object") {
  throw new Error("tokens.json is missing a sports object");
}

if (!Array.isArray(tokens.zones) || tokens.zones.length !== 5) {
  throw new Error("tokens.json zones must contain exactly five entries");
}
tokens.zones.forEach((zone, index) => {
  parseHex(zone.hex);
  if (zone.label !== `Z${index + 1}` || typeof zone.name !== "string" || !zone.name) {
    throw new Error(`invalid zone token at index ${index}`);
  }
});

function cssSportKey(id) {
  if (id === "weight_training") return "weights";
  return id.replace(/_/g, "-");
}

function camelCase(id) {
  return id.replace(/_([a-z])/g, (_, ch) => ch.toUpperCase());
}

function parseHex(hex) {
  const s = String(hex ?? "").trim().replace(/^#/, "");
  if (!/^[0-9A-Fa-f]{6}$/.test(s)) {
    throw new Error(`invalid hex color: ${hex}`);
  }
  return {
    r: parseInt(s.slice(0, 2), 16),
    g: parseInt(s.slice(2, 4), 16),
    b: parseInt(s.slice(4, 6), 16),
  };
}

function hexByte(n) {
  return `0x${n.toString(16).toUpperCase().padStart(2, "0")}`;
}

function swiftColor(hex) {
  const { r, g, b } = parseHex(hex);
  return `Color(red: ${hexByte(r)} / 255.0, green: ${hexByte(g)} / 255.0, blue: ${hexByte(b)} / 255.0)`;
}

const sportVars = Object.entries(tokens.sports)
  .map(([id, sport]) => `  --wi-${cssSportKey(id)}: ${sport.hex};`)
  .join("\n");

const workoutEntries = Object.entries(tokens.workouts ?? {});
const workoutVars = workoutEntries
  .map(([id, workout]) => `  --wi-workout-${id.replace(/_/g, "-")}: ${workout.hex};`)
  .join("\n");

const zoneVars = tokens.zones
  .map((zone, index) => `  --wi-zone-${index + 1}: ${zone.hex};`)
  .join("\n");

const css = `/* Generated by shared/warm-instrument/generate.mjs — do not edit by hand */
.wi-shell {
  --wi-page: ${tokens.palette.desk};
  --wi-surface: ${tokens.palette.paper};
  --wi-surface-muted: ${tokens.palette.surfaceMuted};
  --wi-ink: ${tokens.palette.ink};
  --wi-ink-muted: ${tokens.palette.inkMuted};
  --wi-ink-faint: ${tokens.palette.inkFaint};
  --wi-line: ${tokens.lines.border};
  --wi-line-dashed: ${tokens.lines.borderDashed};
  --wi-rust: ${tokens.palette.accent};
  --wi-rust-dark: ${tokens.palette.accentDark};
${sportVars}
${workoutVars}
${zoneVars}
  --wi-card-shadow: ${tokens.shadows.card};
  --wi-engine-shadow: ${tokens.shadows.engine};
}
`;

const swiftSports = Object.entries(tokens.sports)
  .map(([id, sport]) => `        static let ${camelCase(id)} = ${swiftColor(sport.hex)}`)
  .join("\n");

const swiftWorkouts = workoutEntries
  .map(([id, workout]) => `        static let ${camelCase(id)} = ${swiftColor(workout.hex)}`)
  .join("\n");

const swiftZones = tokens.zones.map((zone) => swiftColor(zone.hex)).join(",\n            ");

const swift = `// Generated by shared/warm-instrument/generate.mjs — do not edit
import SwiftUI

enum WITokens {
    enum Sports {
${swiftSports}
    }

    enum Workouts {
${swiftWorkouts}
    }

    enum Zones {
        static let ramp: [Color] = [
            ${swiftZones}
        ]
    }
}
`;

fs.writeFileSync(CSS_OUT, css);
fs.writeFileSync(SWIFT_OUT, swift);
console.log("✓ wi-tokens.generated.css written");
console.log("✓ WarmInstrumentTokens.generated.swift written");
