/** Compatibility barrel. Shared widget code imports from `@/components/widgets`. */
export type {
  ActivityCellState,
  ActivityInspectionSnapshot,
  ActivityMonthSnapshot,
  BuildPhaseSnapshot,
  CaloriesSnapshot,
  CoachMessageSnapshot,
  CoachReadSnapshot,
  CommitmentSnapshot,
  DoseRowSnapshot,
  EngineSnapshot,
  EngineSnapshotS,
  LoadMixSnapshot,
  PhaseMilestoneSnapshot,
  PlanDaySnapshot,
  QuestSideSnapshot,
  QuestSnapshot,
  QuestSnapshotS,
  RecentSessionSnapshot,
  SportAnalyticsNavLink,
  TrainingActivitySnapshot,
  TrendPointSnapshot,
  Vo2Snapshot,
  WarmHomeSnapshots,
  WarmSportId,
  WeeklyPlanSnapshot,
  WidgetSnapshotsFile,
} from "../widgets/snapshots";
