// Generated by ios/scripts/generate-wi-tokens.swift.mjs — do not edit by hand
import SwiftUI
import UIKit

/// Light-mode base values from `shared/warm-instrument/tokens.json`.
/// `Theme` / `WarmInstrument` wrap these in trait-aware `UIColor` where dark mode differs.
enum WarmInstrumentTokens {
    static func color(hex: String) -> Color {
        var s = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if s.hasPrefix("#") { s.removeFirst() }
        guard s.count == 6, let v = UInt32(s, radix: 16) else { return Color.primary }
        return Color(
            red: Double((v >> 16) & 0xFF) / 255,
            green: Double((v >> 8) & 0xFF) / 255,
            blue: Double(v & 0xFF) / 255
        )
    }

    static func uiColor(hex: String) -> UIColor {
        var s = hex.trimmingCharacters(in: .whitespacesAndNewlines)
        if s.hasPrefix("#") { s.removeFirst() }
        guard s.count == 6, let v = UInt32(s, radix: 16) else { return .label }
        return UIColor(
            red: CGFloat((v >> 16) & 0xFF) / 255,
            green: CGFloat((v >> 8) & 0xFF) / 255,
            blue: CGFloat(v & 0xFF) / 255,
            alpha: 1
        )
    }

    enum Palette {
        static let paper = color(hex: "#fbf8f1")
        static let desk = color(hex: "#e8e2d7")
        static let surfaceMuted = color(hex: "#f3eee3")
        static let ink = color(hex: "#2b2d29")
        static let inkMuted = color(hex: "#75746b")
        static let inkFaint = color(hex: "#98998f")
        static let accent = color(hex: "#7f3728")
        static let accentDark = color(hex: "#652b20")
        static let alarmBg = color(hex: "#e4e4ec")
        static let alarmFg = color(hex: "#4b5578")

        enum UI {
            static let paper = uiColor(hex: "#fbf8f1")
            static let desk = uiColor(hex: "#e8e2d7")
            static let surfaceMuted = uiColor(hex: "#f3eee3")
            static let ink = uiColor(hex: "#2b2d29")
        }
    }

    enum Lines {
        static func borderUIColor(alpha: CGFloat) -> UIColor {
            UIColor(red: CGFloat(84) / 255, green: CGFloat(76) / 255, blue: CGFloat(65) / 255, alpha: alpha)
        }

        static let border = Color(red: Double(84) / 255, green: Double(76) / 255, blue: Double(65) / 255).opacity(0.16)
        static let borderDashed = Color(red: Double(84) / 255, green: Double(76) / 255, blue: Double(65) / 255).opacity(0.35)
        static let headerRule = color(hex: "#d8d2c6")
    }

    enum Shadows {
        static let card = Color(red: Double(57) / 255, green: Double(52) / 255, blue: Double(42) / 255).opacity(0.08)
        static let engine = Color(red: Double(101) / 255, green: Double(43) / 255, blue: Double(32) / 255).opacity(0.18)
    }

    /// `radius.cardIosPt` from tokens.json
    static let cardRadius: CGFloat = 18

    /// Static sport palette from `sports.*.hex`, keyed by `WarmSportId`.
    static let sportColors: [WarmSportId: Color] = [
        .badminton: color(hex: "#315a4a"),
        .calisthenics: color(hex: "#4f587a"),
        .foundation: color(hex: "#6d7d4e"),
        .cycling: color(hex: "#a8702c"),
        .run: color(hex: "#c44020"),
        .strength: color(hex: "#111111"),
        .weightTraining: color(hex: "#3b4a6b"),
        .hike: color(hex: "#8b6f47"),
        .walk: color(hex: "#a8a29e"),
        .cricket: color(hex: "#2dd4bf"),
        .football: color(hex: "#e11d48"),
        .workout: color(hex: "#6b7280"),
        .swim: color(hex: "#0ea5e9"),
    ]
}
