#!/usr/bin/env python3
"""Generate CODEOWNERS from the agent scope map.

The scope map below mirrors AGENTS.md §The Team (source of truth) and the
per-agent "## Scope" sections in .github/agents/*.md.  When the routing table
changes, update this dict first, then re-run the script.

Usage:
    python3 platform/scripts/gen-codeowners.py

Idempotent: a second run with no routing changes produces an identical file
and therefore an empty `git diff CODEOWNERS`.
"""

from __future__ import annotations

import os
import textwrap

# ---------------------------------------------------------------------------
# Scope map — mirrors AGENTS.md §The Team.
# Order matters: GitHub evaluates CODEOWNERS top-to-bottom and the last
# matching rule wins, so list the catch-all (*) first and specific paths last.
# ---------------------------------------------------------------------------
#
# Format: list of (glob_pattern, github_team_slug) tuples, in file order.
# Cyclops is intentionally absent — it is read-only and owns no paths.
#
SCOPE_MAP: list[tuple[str, str]] = [
    # Catch-all: Tech Lead is the fallback reviewer for everything
    ("*",                        "@sibling-shipyard/tech-lead"),

    # React dashboard — UI Expert
    ("ui/client/",               "@sibling-shipyard/ui-expert"),

    # Backend API, engine, observability, build scripts — Bob the Builder
    ("ui/api/",                  "@sibling-shipyard/bob-the-builder"),
    ("engine/",                  "@sibling-shipyard/bob-the-builder"),
    ("ui/observability/",        "@sibling-shipyard/bob-the-builder"),
    ("ui/scripts/",              "@sibling-shipyard/bob-the-builder"),

    # Native iOS app — iOS Builder
    ("ios/",                     "@sibling-shipyard/ios-builder"),

    # Coaching memory, sessions, soul layers — Coach Phelps
    ("user_data/",               "@sibling-shipyard/coach-phelps"),
    ("sessions/",                "@sibling-shipyard/coach-phelps"),
    ("platform/soul/",           "@sibling-shipyard/coach-phelps"),
]

# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

HEADER = textwrap.dedent("""\
    # CODEOWNERS — generated by platform/scripts/gen-codeowners.py
    # Edit that script, not this file.
    # Source of truth: AGENTS.md §The Team + .github/agents/*.md §Scope
    # Cyclops is read-only and owns no paths (intentionally absent).

""")


def generate(scope_map: list[tuple[str, str]]) -> str:
    """Return the full CODEOWNERS file content."""
    lines = [HEADER]
    for pattern, team in scope_map:
        lines.append(f"{pattern:<30} {team}\n")
    return "".join(lines)


def main() -> None:
    # Resolve repo root relative to this script's location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.normpath(os.path.join(script_dir, "..", ".."))
    output_path = os.path.join(repo_root, "CODEOWNERS")

    content = generate(SCOPE_MAP)

    # Read existing file (if any) to check idempotency
    existing: str | None = None
    if os.path.exists(output_path):
        with open(output_path, encoding="utf-8") as fh:
            existing = fh.read()

    if existing == content:
        print(f"CODEOWNERS is already up to date — no changes written.")
        return

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    print(f"Written: {output_path}")


if __name__ == "__main__":
    main()
