#!/usr/bin/env python3
"""Generate CODEOWNERS from the agent scope map.

The scope map below mirrors AGENTS.md §The Team (source of truth) and the
per-agent "## Scope" sections in .github/agents/*.md.  When the routing table
changes, update this dict first, then re-run the script.

Usage:
    python3 platform/scripts/gen-codeowners.py

Idempotent: a second run with no routing changes produces an identical file
and therefore an empty `git diff CODEOWNERS`.
"""

from __future__ import annotations

import os
import textwrap

# ---------------------------------------------------------------------------
# Scope map — mirrors AGENTS.md §The Team.
# Order matters: top-to-bottom and the last matching rule wins, so list the 
# catch-all (*) first and specific paths last.
# ---------------------------------------------------------------------------
#
# Format: list of (glob_pattern, agent_role) tuples, in file order.
# Cyclops is intentionally absent — it is read-only and owns no paths.
# We use agent role names (e.g. Tech-Lead) rather than GitHub @teams so 
# we don't create the illusion of GitHub-native enforcement for unresolvable teams.
#
SCOPE_MAP: list[tuple[str, str]] = [
    # Catch-all: Tech Lead is the fallback reviewer for everything
    ("*",                                  "Tech-Lead"),

    # React dashboard — UI Expert
    ("ui/client/",                         "UI-Expert"),

    # Backend API, engine core, scripts, user data — Bob the Builder
    ("ui/api/",                            "Bob-the-Builder"),
    ("engine/core/",                       "Bob-the-Builder"),
    ("scripts/",                           "Bob-the-Builder"),
    ("ui/observability/",                  "Bob-the-Builder"),
    ("ui/scripts/",                        "Bob-the-Builder"),
    ("user_data/",                         "Bob-the-Builder"),

    # Native iOS app — iOS Builder
    ("ios/",                               "iOS-Builder"),

    # Coaching memory, sessions — Coach Phelps (overrides Bob's user_data/)
    ("user_data/coach/",                   "Coach-Phelps"),
    ("user_data/ledger/challenge_v2.json", "Coach-Phelps"),
    ("sessions/",                          "Coach-Phelps"),
    
    # Soul layers — Tech Lead only (overrides Coach if anything matches, though path is separate)
    ("platform/soul/",                     "Tech-Lead"),
]

# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------

HEADER = textwrap.dedent("""\
    # CODEOWNERS — generated by platform/scripts/gen-codeowners.py
    # Edit that script, not this file.
    # Source of truth: AGENTS.md §The Team + .github/agents/*.md §Scope
    # Cyclops is read-only and owns no paths (intentionally absent).
    #
    # Note: Owners are internal agent roles, not GitHub users/teams. 
    # This file is for agent and CI boundaries, not GitHub UI enforcement.

""")


def generate(scope_map: list[tuple[str, str]]) -> str:
    """Return the full CODEOWNERS file content."""
    lines = [HEADER]
    for pattern, team in scope_map:
        lines.append(f"{pattern:<38} {team}\n")
    return "".join(lines)


def main() -> None:
    # Resolve repo root relative to this script's location
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.normpath(os.path.join(script_dir, "..", ".."))
    output_path = os.path.join(repo_root, "CODEOWNERS")

    content = generate(SCOPE_MAP)

    # Read existing file (if any) to check idempotency
    existing: str | None = None
    if os.path.exists(output_path):
        with open(output_path, encoding="utf-8") as fh:
            existing = fh.read()

    if existing == content:
        print(f"CODEOWNERS is already up to date — no changes written.")
        return

    with open(output_path, "w", encoding="utf-8") as fh:
        fh.write(content)

    print(f"Written: {output_path}")


if __name__ == "__main__":
    main()
